apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: my-app-secrets
  namespace: default
spec:
  backendType: secretsManager
  data:
    - key: "telegram-bot-token"
      name: "ENV_TELEGRAM_BOT_TOKEN"
    - key: "function-name"
      name: "ENV_FUNCTION_NAME"
